src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;


#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cet email')]
#[ORM\Entity(repositoryClass: UsersRepository::class)]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
  #[ORM\Id]
  #[ORM\Column(type: 'uuid', unique: true)]
  #[ORM\GeneratedValue(strategy: 'CUSTOM')]
  #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
  #[Assert\Uuid]
  private ?Uuid $id;

  #[ORM\Column]
  private array $roles = [];

  #[ORM\Column]
  private ?bool $status = null;

  #[ORM\Column(length: 100)]
  #[Assert\NotBlank]
  #[Assert\Length(min: 3, minMessage: "Veuillez avoir au moins 3 caractères")]
  private ?string $firstname = null;

  #[ORM\Column(length: 100)]
  #[Assert\NotBlank]
  #[Assert\Length(min: 3, minMessage: "Veuillez avoir au moins 3 caractères")]
  private ?string $lastname = null;

  #[ORM\Column(length: 180, unique: true)]
  private ?string $email = null;

  /**
   * @var string The hashed password
   */
  #[ORM\Column]
  #[Assert\Regex(
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$",
    message: "Le mot de passe doit contenir au minimum 8 caractères avec une minuscule, une majuscule, un caractère spécial et un chiffre."
  )]
  private ?string $password = null;

  #[ORM\Column(type: 'boolean')]
  private $is_verified = false;

  #[ORM\Column(type: 'string', length: 100, nullable: true)]
  private $resetToken = null;

  #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
  #[ORM\JoinColumn(onDelete: 'CASCADE')]
  private ?Franchises $franchise = null;

  #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
  #[ORM\JoinColumn(onDelete: 'CASCADE')]
  private ?Structures $structure = null;

  public function getId(): ?Uuid
  {
    return $this->id;
  }

  /**
   * @see UserInterface
   */
  public function getRoles(): array
  {
    $roles = $this->roles;
    $roles[] = 'ROLE_USER';

    return array_unique($roles);
  }

  public function setRoles(array $roles): self
  {
    $this->roles = $roles;

    return $this;
  }

  public function isStatus(): ?bool
  {
    return $this->status;
  }

  public function setStatus(bool $status): self
  {
    $this->status = $status;

    return $this;
  }

  public function getFirstname(): ?string
  {
    return $this->firstname;
  }

  public function setFirstname(string $firstname): self
  {
    $this->firstname = $firstname;

    return $this;
  }

  public function getLastname(): ?string
  {
    return $this->lastname;
  }

  public function setLastname(string $lastname): self
  {
    $this->lastname = $lastname;

    return $this;
  }

  public function getEmail(): ?string
  {
    return $this->email;
  }
  
  public function setEmail(string $email): self
  {
    $this->email = $email;
    
    return $this;
  }
  
  /**
   * A visual identifier that represents this user.
   *
   * @see UserInterface
   */
  public function getUserIdentifier(): string
  {
    return (string)$this->email;
  }
  

  /**
   * @see PasswordAuthenticatedUserInterface
   */
  public function getPassword(): string
  {
    return $this->password;
  }
  
  public function setPassword(string $password): self
  {
    $this->password = $password;
    
    return $this;
  }
  
  /**
   * @see UserInterface
   */
  public function eraseCredentials()
  {
    // If you store any temporary, sensitive data on the user, clear it here
    // $this->plainPassword = null;
  }

  public function getIsVerified(): ?bool
  {
    return $this->is_verified;
  }

  public function setIsVerified(bool $is_verified): self
  {
    $this->is_verified = $is_verified;

    return $this;
  }

  public function getResetToken(): ?string
  {
    return $this->resetToken;
  }

  public function setResetToken(?string $resetToken): self
  {
    $this->resetToken = $resetToken;

    return $this;
  }

  public function getFranchise(): ?Franchises
  {
      return $this->franchise;
  }

  public function setFranchise(?Franchises $franchise): self
  {
      $this->franchise = $franchise;

      return $this;
  }

  public function getStructure(): ?Structures
  {
      return $this->structure;
  }

  public function setStructure(?Structures $structure): self
  {
      $this->structure = $structure;

      return $this;
  }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Accueil{% endblock %} - CrossFit life</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Montserrat+Alternates:wght@500&display=swap" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <! -- Feuilles de styles -->
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">

        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        <! -- Fichiers JS -->

        <script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}" defer></script>

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}

    </head>
    <body>
    <div class="contain">
        <div class="sidebar">
            <ul >
                <li>
                    <a href="#" class="logo">
                        <span class="icon"><i class='bx bx-dumbbell'></i></span>
                        <span class="links_name fw-bold">CrossFit Life</span>
                    </a>
                </li>
                {% if is_granted('ROLE_ADMIN') %}
                <li>
                    <a href="{{ path('franchises_index') }}">
                        <span class="icon"><i class='bx bx-sitemap'></i></span>
                        <span class="links_name">Franchises</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('structures_index') }}">
                        <span class="icon"><i class='bx bxs-home-heart' ></i></span>
                        <span class="links_name">Structures</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('droits_index') }}">
                        <span class="icon"><i class='bx bx-toggle-right'></i></span>
                        <span class="links_name">Droits</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('admin_utilisateurs') }}">
                        <span class="icon"><i class='bx bx-user' ></i></span>
                        <span class="links_name">Utilisateurs</span>
                    </a>
                </li>
                {% elseif is_granted('ROLE_PARTNER') %}
                <li>
                    <a href="{{ path('partenaire_index') }}">
                        <span class="icon"><i class='bx bx-grid-alt' ></i></span>
                        <span class="links_name">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('profile_index') }}">
                        <span class="icon"><i class='bx bx-user' ></i></span>
                        <span class="links_name">Profil</span>
                    </a>
                </li>
                {% elseif is_granted('ROLE_MANAGER') %}
                <li>
                    <a href="{{ path('manager_index') }}">
                        <span class="icon"><i class='bx bx-grid-alt' ></i></span>
                        <span class="links_name">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('profile_index') }}">
                        <span class="icon"><i class='bx bx-user' ></i></span>
                        <span class="links_name">Profil</span>
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{{ path('app_logout') }}">
                        <span class="icon"><i class='bx bx-log-out' id="log_out"></i></span>
                        <span class="links_name">Déconnecter</span>
                    </a>
                </li>
                <li>
                    <a href="{{ path('legal_mention') }}">
                        <span class="icon"><i class='bx bxs-shield-plus' ></i></span>
                        <span class="links_name">Mentions légales</span>
                    </a>
                </li>
            </ul>
            <div class="profile_content">
                <div class="profile">
                    <div class="profile_details">
                        <img src="{{ asset('assets/img/logo_registration.jpg') }}" alt="">
                        <div class="rol_email">
                            <div class="email">{{ app.user.email }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <i class='bx bx-menu' id="btn"></i>
                </div>
            </div>

            {% if app.user and app.user.isVerified == false %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                    aria-label="Close"></button>
                    <div class="alert-message">
                        <strong>Votre compte n'est pas activé</strong>,<a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
                    </div>
                </div>
            {% endif %}

            {% include "_partials/_flash.html.twig" %}

            {% block body %}{% endblock %}
        </div>
    </div>
    </body>
    <script>
        let toggle = document.querySelector('.toggle');
        let navigation = document.querySelector('.sidebar');
        let main = document.querySelector('.main');

        toggle.onclick = function() {
            navigation.classList.toggle('active');
            main.classList.toggle('active')
        }
    </script>
</html>